name: Rootcore
version: '1.3'
main: me.cyro.rootcore.Rootcore
api-version: '1.21'
commands:
  leaderboard:
    description: leaderboard stuff
    permission: rootcore.admin
  autocomp:
    description: auto comp settings
  lobby:
    description: sends you back to the lobby
  tutorial:
    description: shows tutorials for the root core networks gamemodes
  rootcorereloadconfig:
    description: reloads rootcore config; admin only
    permission: rootcore.admin
softdepend:
  - DecentHolograms